export const REQUEST_GET_ALL_TRAINS = "REQUEST_GET_ALL_TRAINS"
export const REQUEST_GET_ALL_TRAINS_SUCCESS = "REQUEST_GET_ALL_TRAINS_SUCCESS"
export const REQUEST_GET_ALL_TRAINS_ERROR = "REQUEST_GET_ALL_TRAINS_ERROR"

export const REQUEST_GET_TRAIN = "REQUEST_GET_TRAIN"
export const REQUEST_GET_TRAIN_SUCCESS = "REQUEST_GET_TRAIN_SUCCESS"
export const REQUEST_GET_TRAIN_ERROR = "REQUEST_GET_TRAIN_ERROR"
